stages:
  - test

unit-test:
  image: node:alpine
  before_script:
    - npm ci
  script:
    - npm run test
  tags:
    - personal

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
